name: Build bundle
on:
  push:
    branches: [ "tilegroxy" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "tilegroxy" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Build
      run: |
        npm install
        gulp bundle
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/ui-bundle.zip
